import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { CreditCard, Truck, Shield } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
const PlacingOrder = ({ orderSummary, handlePlacingOrder, isPending }) => {
    return (_jsx("div", { children: _jsx("div", { className: "lg:sticky lg:top-8 lg:h-fit", children: _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Order Summary" }) }), _jsxs(CardContent, { className: "space-y-4", children: [_jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "Subtotal" }), _jsxs("span", { children: ["$", orderSummary.subtotal.toFixed(2)] })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "Shipping" }), _jsx("span", { children: orderSummary.shipping === 0 ? "Free" : `$${orderSummary.shipping.toFixed(2)}` })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "Tax" }), _jsxs("span", { children: ["$", orderSummary.tax.toFixed(2)] })] }), _jsx(Separator, {}), _jsxs("div", { className: "flex justify-between font-semibold text-lg", children: [_jsx("span", { children: "Total" }), _jsxs("span", { children: ["$", orderSummary.total.toFixed(2)] })] })] }), _jsxs(Button, { className: "w-full", size: "lg", disabled: isPending, onClick: handlePlacingOrder, children: [_jsx(CreditCard, { className: "mr-2 h-5 w-5" }), isPending ? (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin" }), _jsx("span", { children: "Placing..." })] }))
                                        : "Place Order"] }), _jsxs("div", { className: "space-y-3 pt-4", children: [_jsxs("div", { className: "flex items-center gap-2 text-sm text-gray-600", children: [_jsx(Shield, { className: "h-4 w-4" }), _jsx("span", { children: "Secure checkout with SSL encryption" })] }), _jsxs("div", { className: "flex items-center gap-2 text-sm text-gray-600", children: [_jsx(Truck, { className: "h-4 w-4" }), _jsx("span", { children: "Free returns within 30 days" })] })] })] })] }) }) }));
};
export default PlacingOrder;
