import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
const Header = () => {
    return (_jsx("section", { className: "relative overflow-hidden bg-gradient-to-br from-primary/20 via-background to-secondary/20", children: _jsx("div", { className: "container md:pl-20  md:pt-24 md:pb-20", children: _jsxs("div", { className: "grid lg:grid-cols-2 gap-12 items-center", children: [_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { className: "space-y-4", children: [_jsx(Badge, { className: "w-fit", children: "New Drop" }), _jsx("h1", { className: "text-4xl md:text-6xl font-bold tracking-tight", children: " Level Up Your Style Game" }), _jsx("p", { className: "text-xl text-muted-foreground max-w-lg", children: "Discover the latest arrivals, exclusive offers, and shop alongside thousands of trendsetters. Your next favorite look is just a click away.                " })] }), _jsx("div", { className: "flex flex-col sm:flex-row gap-4", children: _jsx(Link, { to: "/search", children: _jsxs(Button, { size: "lg", className: "text-lg px-8", children: ["Browse Collections", _jsx(ArrowRight, { className: "ml-2 h-5 w-5" })] }) }) }), _jsxs("div", { className: "flex items-center gap-8 pt-4", children: [_jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-2xl font-bold", children: "10M+" }), _jsx("div", { className: "text-sm text-muted-foreground", children: "Active Buyers" })] }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-2xl font-bold", children: "5000+" }), _jsx("div", { className: "text-sm text-muted-foreground", children: "Fits Available" })] }), _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-2xl font-bold", children: "4.9\u2605" }), _jsx("div", { className: "text-sm text-muted-foreground", children: "User Rating" })] })] })] }), _jsxs("div", { className: "relative", children: [_jsx("div", { className: "relative z-10", children: _jsx("img", { src: "./Brand shoot\uD83C\uDF1F.jpg", alt: "Featured Game", width: 800, height: 600, className: "rounded-2xl shadow-2xl" }) }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-primary/20 to-transparent rounded-2xl" })] })] }) }) }));
};
export default Header;
